export const THEME_CONTRACT_VERSION = 2 as const;

export const THEME_RUNTIME_THEME_MODE_ATTRIBUTE = "data-fishmark-theme-mode";

export const THEME_RUNTIME_ENV_CSS_VARS = {
  wordCount: "--fishmark-env-word-count",
  readingMode: "--fishmark-env-reading-mode",
  viewportWidth: "--fishmark-env-viewport-width",
  viewportHeight: "--fishmark-env-viewport-height"
} as const;

export const THEME_SEMANTIC_STYLE_SLOTS = [
  "app.bg",
  "workspace.bg",
  "rail.bg",
  "panel.bg",
  "panel.border",
  "panel.shadow",
  "statusbar.bg",
  "statusbar.border",
  "titlebar.bg",
  "text.primary",
  "text.secondary",
  "text.muted",
  "text.accent",
  "text.danger",
  "text.onAccent",
  "control.bg",
  "control.bgHover",
  "control.bgActive",
  "control.border",
  "control.fg",
  "focus.ring",
  "selection.bg",
  "selection.fg",
  "banner.info.bg",
  "banner.warning.bg",
  "banner.error.bg",
  "editor.bg",
  "editor.fg",
  "editor.muted",
  "editor.caret",
  "editor.currentLine.bg",
  "editor.gutter.fg",
  "editor.activeBlock.bg",
  "editor.activeBlock.border",
  "markdown.body",
  "markdown.heading",
  "markdown.headingMarker",
  "markdown.link",
  "markdown.linkHover",
  "markdown.strong",
  "markdown.emphasis",
  "markdown.quote.fg",
  "markdown.quote.border",
  "markdown.list.bullet",
  "markdown.list.text",
  "markdown.task.done",
  "markdown.hr",
  "markdown.inlineCode.fg",
  "markdown.inlineCode.bg",
  "markdown.code.fg",
  "markdown.code.bg",
  "markdown.code.border",
  "markdown.table.border",
  "markdown.table.header.bg",
  "markdown.table.header.fg",
  "markdown.table.cell.bg",
  "markdown.table.rowStripe",
  "markdown.codeToken.keyword",
  "markdown.codeToken.string",
  "markdown.codeToken.number",
  "markdown.codeToken.comment",
  "markdown.codeToken.function",
  "markdown.codeToken.type"
] as const;
